//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillList.CharecterServiceRefrence {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CharecterData", Namespace="http://schemas.datacontract.org/2004/07/CharecterInfoWCF")]
    [System.SerializableAttribute()]
    public partial class CharecterData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HateRaitingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guild {
            get {
                return this.GuildField;
            }
            set {
                if ((object.ReferenceEquals(this.GuildField, value) != true)) {
                    this.GuildField = value;
                    this.RaisePropertyChanged("Guild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HateRaiting {
            get {
                return this.HateRaitingField;
            }
            set {
                if ((this.HateRaitingField.Equals(value) != true)) {
                    this.HateRaitingField = value;
                    this.RaisePropertyChanged("HateRaiting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Race {
            get {
                return this.RaceField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceField, value) != true)) {
                    this.RaceField = value;
                    this.RaisePropertyChanged("Race");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Spec {
            get {
                return this.SpecField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecField, value) != true)) {
                    this.SpecField = value;
                    this.RaisePropertyChanged("Spec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CharecterServiceRefrence.ICharecterService")]
    public interface ICharecterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharecterService/GetData", ReplyAction="http://tempuri.org/ICharecterService/GetDataResponse")]
        KillList.CharecterServiceRefrence.CharecterData[] GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICharecterService/GetData", ReplyAction="http://tempuri.org/ICharecterService/GetDataResponse")]
        System.Threading.Tasks.Task<KillList.CharecterServiceRefrence.CharecterData[]> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICharecterServiceChannel : KillList.CharecterServiceRefrence.ICharecterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CharecterServiceClient : System.ServiceModel.ClientBase<KillList.CharecterServiceRefrence.ICharecterService>, KillList.CharecterServiceRefrence.ICharecterService {
        
        public CharecterServiceClient() {
        }
        
        public CharecterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CharecterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharecterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CharecterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KillList.CharecterServiceRefrence.CharecterData[] GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<KillList.CharecterServiceRefrence.CharecterData[]> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
